package amusementparkmanager.entities;
// Generated Jan 16, 2019 3:49:40 PM by Hibernate Tools 4.3.1

import java.util.Set;


/**
 * Installation generated by hbm2java
 */
public class Installation implements java.io.Serializable {

    private Integer installationId;
    private String name;
    private Integer minAge;
    private Set<Park> parks;
    
    public Installation() {
    }

    public Installation(String name, Integer minAge) {
        this.name = name;
        this.minAge = minAge;
    }

    public Integer getInstallationId() {
        return this.installationId;
    }

    public void setInstallationId(Integer installationId) {
        this.installationId = installationId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getMinAge() {
        return this.minAge;
    }

    public void setMinAge(Integer minAge) {
        this.minAge = minAge;
    }
    
    @Override
    public String toString() {
        return name;
    }

    public Set<Park> getParks() {
        return parks;
    }

    public void setParks(Set<Park> parks) {
        this.parks = parks;
    }
    
}
