package amusementparkmanager.entities;
// Generated Jan 16, 2019 3:49:40 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Manager generated by hbm2java
 */
public class Manager implements java.io.Serializable {

    private Integer managerId;
    private String name;
    private Double salary;
    private Set parks = new HashSet(0);
    private Integer salaryIncreased;

    public Manager() {
    }

    public Manager(String name, Double salary, Integer salaryIncreased) {
        this.name = name;
        this.salary = salary;
        this.salaryIncreased = salaryIncreased;
    }

    public Manager(String name, Double salary, Integer salaryIncreased, Set parks) {
        this.name = name;
        this.salary = salary;
        this.salaryIncreased = salaryIncreased;
        this.parks = parks;
    }

    public Integer getManagerId() {
        return this.managerId;
    }

    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Double getSalary() {
        return this.salary;
    }

    public void setSalary(Double salary) {
        this.salary = salary;
    }

    public Set getParks() {
        return this.parks;
    }

    public void setParks(Set parks) {
        this.parks = parks;
    }

    public void increaseSalary(Integer percent) {
        if (salaryIncreased == null) {
            salaryIncreased = 0;
        }
        if (salaryIncreased < 1) {
            salary += salary / 100 * percent;
            salaryIncreased = 1;
        }
    }

    public Integer getSalaryIncreased() {
        return salaryIncreased;
    }

    public void setSalaryIncreased(Integer salaryIncreased) {
        this.salaryIncreased = salaryIncreased;
    }

    @Override
    public String toString() {
        return name;
    }

}
